//inspire_hand_touch.idl
module inspire
{
    struct inspire_hand_touch
    {
        sequence<int16,9>   fingerone_tip_touch;      // Pinky finger tip tactile data
        sequence<int16,96>  fingerone_top_touch;      // Pinky finger top tactile data
        sequence<int16,80>  fingerone_palm_touch;     // Pinky finger palm tactile data
        sequence<int16,9>   fingertwo_tip_touch;      // Ring finger tip tactile data
        sequence<int16,96>  fingertwo_top_touch;      // Ring finger top tactile data
        sequence<int16,80>  fingertwo_palm_touch;     // Ring finger palm tactile data
        sequence<int16,9>   fingerthree_tip_touch;    // Middle finger tip tactile data
        sequence<int16,96>  fingerthree_top_touch;    // Middle finger top tactile data
        sequence<int16,80>  fingerthree_palm_touch;   // Middle finger palm tactile data
        sequence<int16,9>   fingerfour_tip_touch;     // Index finger tip tactile data
        sequence<int16,96>  fingerfour_top_touch;     // Index finger top tactile data
        sequence<int16,80>  fingerfour_palm_touch;    // Index finger palm tactile data
        sequence<int16,9>   fingerfive_tip_touch;     // Thumb tip tactile data
        sequence<int16,96>  fingerfive_top_touch;     // Thumb top tactile data
        sequence<int16,9>   fingerfive_middle_touch;  // Thumb middle tactile data
        sequence<int16,96>  fingerfive_palm_touch;    // Thumb palm tactile data
        sequence<int16,112> palm_touch;                // Palm tactile data
    };

};
